apiVersion: v1
kind: List
metadata:
  name: list-svc-{{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}      
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-{{ .Release.Name }}-db
      namespace: {{ .Release.Namespace }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      type: {{ .Values.mariadb.service.type }}
      clusterIP: {{ .Values.mariadb.service.clusterIP }}
      loadBalancerIP: {{ .Values.mariadb.service.loadBalancerIP }}
      ipFamilyPolicy: {{ .Values.mariadb.service.ipFamilyPolicy }}
      ports:
      - name: db
        port: {{ .Values.mariadb.service.ports.db }}
        protocol: TCP
        targetPort: 3306
      selector: 
        app: {{ .Release.Name }}-db
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-{{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}      
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      type: {{ .Values.pdns.service.type }}
      loadBalancerIP: {{ .Values.pdns.service.loadBalancerIP }}
      clusterIP: {{ .Values.pdns.service.clusterIP }}
      ipFamilyPolicy: {{ .Values.pdns.service.ipFamilyPolicy }}
      ports:
      - name: dns
        port: {{ .Values.pdns.service.ports.dns }}
        protocol: TCP
        targetPort: 5353
      - name: api
        port: {{ .Values.pdns.service.ports.api }}
        protocol: TCP
        targetPort: 8081
      selector:
        app: {{ .Release.Name }}